Vagrant.configure("2") do |config|

 config.vm.box = "ubuntu/xenial64"
# creating a virtual machine ubuntu 


# assign private ip to our VM
 config.vm.network "private_network", ip: "192.168.10.100"   

 # Ensure to install hostsupdater plugin on our localhost before rerunning the vagrant
 config.hostsupdater.aliases = ["development.local"]

# sync folder from os to vm
            # "." means current location - into / inside our vm
 config.vm.synced_folder 'app', '/home/vagrant/app'
 config.vm.synced_folder 'sites-available', '/etc/nginx/sites-available'

  # run bash file - provisioning instructions
  config.vm.provision 'shell', path: '~/app/app/provision.sh'
end
